---

- name: devops.repos
  src: https://github.com/hmcts/repos-role.git
  scm: git
  version: master

- name: devops.common
  src: https://github.com/hmcts/common-role.git
  scm: git
  version: RDO-1967-requirements-coding-in-the-open

- name: devops.java
  src: https://github.com/hmcts/java-role.git
  scm: git
  version: master

- name: devops.docker
  src: https://github.com/hmcts/docker-role.git
  scm: git
  version: master

- name: devops.azure-cli
  src: https://github.com/hmcts/azure-cli-role.git
  scm: git
  version: master

- name: devops.vault-token
  src: https://github.com/hmcts/vault-token-role.git
  scm: git
  version: master
