---

- name: devops.repos
  src: git@git.reform.hmcts.net:devops/repos-role.git
  scm: git
  version: master

- name: devops.common
  src: https://github.com/hmcts/common-role.git
  scm: git
  version: master

- name: devops.java
  src: git@git.reform.hmcts.net:devops/java-role.git
  scm: git
  version: master

- name: devops.docker
  src: git@git.reform.hmcts.net:devops/docker-role.git
  scm: git
  version: master

- name: devops.azure-cli
  src: git@git.reform.hmcts.net:devops/azure-cli-role.git
  scm: git
  version: master

- name: devops.vault-token
  src: git@git.reform.hmcts.net:devops/vault-token-role.git
  scm: git
  version: master
