---
- name: "Install yum dependencies"
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_common_role_yum_packages }}"

- name: "Install ruby gems"
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present
  with_items: "{{ jenkins_common_role_ruby_gems }}"

- name: "Install dependencies from pip"
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ jenkins_common_role_pip_packages }}"
